apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: phpmyadmin-hpa
  labels:
    app: phpmyadmin
    tier: administration
spec:
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 85
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: phpmyadmin-deployment
