apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  labels:
    app: wordpress
    tier: frontend
type: Opaque
data:
  WORDPRESS_DB_USER: amhvbmF0YW4=
  WORDPRESS_DB_PASSWORD: cDRzc3cwcmQ=
  WORDPRESS_DB_NAME: azhzX2RhdGFiYXNl
  WORDPRESS_ROOT_PASSWORD: cm9vdA==
