apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
    tier: database
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_USER: amhvbmF0YW4=
  MYSQL_PASSWORD: cDRzc3cwcmQ=
  MYSQL_DATABASE: azhzX2RhdGFiYXNl
